-- ══════════════════════════════════════════════════════════════════════
-- MIGRACIÓN: Tabla clientes (Fase 1 - Esquema, aditivo)
-- ──────────────────────────────────────────────────────────────────────
-- Crea la tabla clientes con relación 1-a-1 a leads (lead_id UNIQUE).
-- Añade cliente_id a fundae_seguimiento (nullable, convive con lead_id).
-- NO toca lead_billing, leads ni el código existente.
-- Idempotente: seguro de re-ejecutar.
-- ══════════════════════════════════════════════════════════════════════

-- ─────────────────────────────────────────────
-- 1. TABLA: clientes
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.clientes (
    id                       bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id                  bigint        UNIQUE REFERENCES public.leads(id) ON DELETE SET NULL,

    -- Datos fiscales / comerciales (movidos desde leads)
    razon_social             text,
    cif                      text,
    domicilio                text,
    codigo_postal            text,
    poblacion                text,
    provincia                text,
    telefono_empresa         text,

    -- Datos FUNDAE / laborales
    ccc                      text,
    cnae                     text,
    convenio_referencia      text,
    num_medio_empleados      text,
    representante_empresa    text,
    nif_nie_representante    text,

    -- Metadatos
    fecha_conversion         timestamptz   DEFAULT now(),
    fecha_creacion           timestamptz   DEFAULT now(),
    updated_at               timestamptz   DEFAULT now()
);

COMMENT ON TABLE  public.clientes IS 'Clientes (lead convertido). 1-a-1 con leads vía lead_id. lead_id nullable para permitir altas directas en el futuro.';
COMMENT ON COLUMN public.clientes.lead_id IS 'Lead de origen. UNIQUE (un lead solo puede convertirse en un cliente). Nullable por si en el futuro se da de alta un cliente sin lead.';

CREATE INDEX IF NOT EXISTS idx_clientes_lead_id        ON public.clientes(lead_id);
CREATE INDEX IF NOT EXISTS idx_clientes_cif            ON public.clientes(cif);
CREATE INDEX IF NOT EXISTS idx_clientes_fecha_creacion ON public.clientes(fecha_creacion DESC);

-- Trigger: auto-update de updated_at
DROP TRIGGER IF EXISTS set_updated_at_clientes ON public.clientes;
CREATE TRIGGER set_updated_at_clientes
    BEFORE UPDATE ON public.clientes
    FOR EACH ROW
    EXECUTE FUNCTION public.update_updated_at();


-- ─────────────────────────────────────────────
-- 2. RLS: clientes (mismo patrón que leads)
-- ─────────────────────────────────────────────
ALTER TABLE public.clientes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "clientes_select" ON public.clientes;
CREATE POLICY "clientes_select" ON public.clientes
  FOR SELECT TO authenticated
  USING (true);

DROP POLICY IF EXISTS "clientes_insert" ON public.clientes;
CREATE POLICY "clientes_insert" ON public.clientes
  FOR INSERT TO authenticated
  WITH CHECK (true);

DROP POLICY IF EXISTS "clientes_update" ON public.clientes;
CREATE POLICY "clientes_update" ON public.clientes
  FOR UPDATE TO authenticated
  USING (true);

DROP POLICY IF EXISTS "clientes_delete" ON public.clientes;
CREATE POLICY "clientes_delete" ON public.clientes
  FOR DELETE TO authenticated
  USING (public.is_admin());


-- ─────────────────────────────────────────────
-- 3. FK en tablas dependientes (cliente_id, nullable de momento)
-- ─────────────────────────────────────────────
ALTER TABLE public.fundae_seguimiento
  ADD COLUMN IF NOT EXISTS cliente_id bigint REFERENCES public.clientes(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_fundae_cliente_id ON public.fundae_seguimiento(cliente_id);


-- ─────────────────────────────────────────────
-- 4. REALTIME
-- ─────────────────────────────────────────────
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime' AND tablename = 'clientes'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.clientes;
  END IF;
END $$;


-- ─────────────────────────────────────────────
-- 5. VERIFICACIÓN
-- ─────────────────────────────────────────────
SELECT
  (SELECT count(*) FROM information_schema.tables WHERE table_schema='public' AND table_name='clientes') AS tabla_clientes,
  (SELECT count(*) FROM information_schema.columns WHERE table_schema='public' AND table_name='fundae_seguimiento' AND column_name='cliente_id') AS fundae_cliente_id,
  (SELECT count(*) FROM pg_policies WHERE schemaname='public' AND tablename='clientes') AS politicas_clientes;
